version: '3.8'

services:
  fabagent:
    build: .
    ports:
      - "8501:8501"  # Streamlit app
      - "8000:8000"  # FastAPI backend
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
